// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pnp.proto

/*
Package pnp is a generated protocol buffer package.

It is generated from these files:
	pnp.proto

It has these top-level messages:
	ClientInfo
	CommonClientInfo
	ClientPkgRequest
	CommonServerResponse
	ServerInstructionPayload
	PackageDetails
	ServerPkgResponse
*/
package pnp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/ZTP/pnp/common/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClientMsgType int32

const (
	ClientMsgType_AUTHENTICATE_CLIENT       ClientMsgType = 0
	ClientMsgType_PKG_ENV_INIT              ClientMsgType = 1
	ClientMsgType_PKG_ENV_INITIALIZED       ClientMsgType = 2
	ClientMsgType_PKG_ENV_INITIALIZE_FAILED ClientMsgType = 3
	ClientMsgType_PKG_NOT_INSTALLED         ClientMsgType = 4
	ClientMsgType_PKG_INSTALLED             ClientMsgType = 5
	ClientMsgType_PKG_VERSION_OUTDATED      ClientMsgType = 6
	ClientMsgType_PKG_VERSION_LATEST        ClientMsgType = 7
	ClientMsgType_PKG_UNINSTALL_SUCCESS     ClientMsgType = 8
	ClientMsgType_PKG_UNINSTALL_FAILED      ClientMsgType = 9
	ClientMsgType_PKG_INSTALL_SUCCESS       ClientMsgType = 10
	ClientMsgType_PKG_INSTALL_FAILED        ClientMsgType = 11
	ClientMsgType_PKG_ROLLBACK_SUCCESS      ClientMsgType = 12
	ClientMsgType_PKG_ROLLBACK_FAILED       ClientMsgType = 13
	ClientMsgType_GET_NEXT                  ClientMsgType = 14
)

var ClientMsgType_name = map[int32]string{
	0:  "AUTHENTICATE_CLIENT",
	1:  "PKG_ENV_INIT",
	2:  "PKG_ENV_INITIALIZED",
	3:  "PKG_ENV_INITIALIZE_FAILED",
	4:  "PKG_NOT_INSTALLED",
	5:  "PKG_INSTALLED",
	6:  "PKG_VERSION_OUTDATED",
	7:  "PKG_VERSION_LATEST",
	8:  "PKG_UNINSTALL_SUCCESS",
	9:  "PKG_UNINSTALL_FAILED",
	10: "PKG_INSTALL_SUCCESS",
	11: "PKG_INSTALL_FAILED",
	12: "PKG_ROLLBACK_SUCCESS",
	13: "PKG_ROLLBACK_FAILED",
	14: "GET_NEXT",
}
var ClientMsgType_value = map[string]int32{
	"AUTHENTICATE_CLIENT":       0,
	"PKG_ENV_INIT":              1,
	"PKG_ENV_INITIALIZED":       2,
	"PKG_ENV_INITIALIZE_FAILED": 3,
	"PKG_NOT_INSTALLED":         4,
	"PKG_INSTALLED":             5,
	"PKG_VERSION_OUTDATED":      6,
	"PKG_VERSION_LATEST":        7,
	"PKG_UNINSTALL_SUCCESS":     8,
	"PKG_UNINSTALL_FAILED":      9,
	"PKG_INSTALL_SUCCESS":       10,
	"PKG_INSTALL_FAILED":        11,
	"PKG_ROLLBACK_SUCCESS":      12,
	"PKG_ROLLBACK_FAILED":       13,
	"GET_NEXT":                  14,
}

func (x ClientMsgType) String() string {
	return proto.EnumName(ClientMsgType_name, int32(x))
}
func (ClientMsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ServerMsgType int32

const (
	ServerMsgType_CLIENT_AUTHENTICATED  ServerMsgType = 0
	ServerMsgType_INITIALIZE_ENV        ServerMsgType = 1
	ServerMsgType_IS_PKG_INSTALLED      ServerMsgType = 2
	ServerMsgType_INSTALL_PKG           ServerMsgType = 3
	ServerMsgType_INSTALL_PKG_FROM_FILE ServerMsgType = 4
	ServerMsgType_IS_PKG_OUTDATED       ServerMsgType = 5
	ServerMsgType_UNINSTALL_PKG         ServerMsgType = 6
	ServerMsgType_ROLLBACK_PKG          ServerMsgType = 7
	ServerMsgType_GET_NEXT_PKG          ServerMsgType = 8
)

var ServerMsgType_name = map[int32]string{
	0: "CLIENT_AUTHENTICATED",
	1: "INITIALIZE_ENV",
	2: "IS_PKG_INSTALLED",
	3: "INSTALL_PKG",
	4: "INSTALL_PKG_FROM_FILE",
	5: "IS_PKG_OUTDATED",
	6: "UNINSTALL_PKG",
	7: "ROLLBACK_PKG",
	8: "GET_NEXT_PKG",
}
var ServerMsgType_value = map[string]int32{
	"CLIENT_AUTHENTICATED":  0,
	"INITIALIZE_ENV":        1,
	"IS_PKG_INSTALLED":      2,
	"INSTALL_PKG":           3,
	"INSTALL_PKG_FROM_FILE": 4,
	"IS_PKG_OUTDATED":       5,
	"UNINSTALL_PKG":         6,
	"ROLLBACK_PKG":          7,
	"GET_NEXT_PKG":          8,
}

func (x ServerMsgType) String() string {
	return proto.EnumName(ServerMsgType_name, int32(x))
}
func (ServerMsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ServerCmdType int32

const (
	ServerCmdType_RUN           ServerCmdType = 0
	ServerCmdType_INFO          ServerCmdType = 1
	ServerCmdType_CLOSE_CONN    ServerCmdType = 2
	ServerCmdType_MANUAL_UPDATE ServerCmdType = 3
)

var ServerCmdType_name = map[int32]string{
	0: "RUN",
	1: "INFO",
	2: "CLOSE_CONN",
	3: "MANUAL_UPDATE",
}
var ServerCmdType_value = map[string]int32{
	"RUN":           0,
	"INFO":          1,
	"CLOSE_CONN":    2,
	"MANUAL_UPDATE": 3,
}

func (x ServerCmdType) String() string {
	return proto.EnumName(ServerCmdType_name, int32(x))
}
func (ServerCmdType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ClientInfo struct {
	OsType   string `protobuf:"bytes,1,opt,name=osType" json:"osType,omitempty"`
	OsFlavor string `protobuf:"bytes,2,opt,name=osFlavor" json:"osFlavor,omitempty"`
	ArchType string `protobuf:"bytes,3,opt,name=archType" json:"archType,omitempty"`
	MACAddr  string `protobuf:"bytes,4,opt,name=MAC_addr,json=MACAddr" json:"MAC_addr,omitempty"`
}

func (m *ClientInfo) Reset()                    { *m = ClientInfo{} }
func (m *ClientInfo) String() string            { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()               {}
func (*ClientInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ClientInfo) GetOsType() string {
	if m != nil {
		return m.OsType
	}
	return ""
}

func (m *ClientInfo) GetOsFlavor() string {
	if m != nil {
		return m.OsFlavor
	}
	return ""
}

func (m *ClientInfo) GetArchType() string {
	if m != nil {
		return m.ArchType
	}
	return ""
}

func (m *ClientInfo) GetMACAddr() string {
	if m != nil {
		return m.MACAddr
	}
	return ""
}

type CommonClientInfo struct {
	RequestHeader *common.RequestHeader `protobuf:"bytes,1,opt,name=requestHeader" json:"requestHeader,omitempty"`
	ClientInfo    *ClientInfo           `protobuf:"bytes,2,opt,name=clientInfo" json:"clientInfo,omitempty"`
}

func (m *CommonClientInfo) Reset()                    { *m = CommonClientInfo{} }
func (m *CommonClientInfo) String() string            { return proto.CompactTextString(m) }
func (*CommonClientInfo) ProtoMessage()               {}
func (*CommonClientInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CommonClientInfo) GetRequestHeader() *common.RequestHeader {
	if m != nil {
		return m.RequestHeader
	}
	return nil
}

func (m *CommonClientInfo) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

type ClientPkgRequest struct {
	CommonClientInfo *CommonClientInfo `protobuf:"bytes,1,opt,name=commonClientInfo" json:"commonClientInfo,omitempty"`
	ClientMsgType    ClientMsgType     `protobuf:"varint,2,opt,name=clientMsgType,enum=pnp.ClientMsgType" json:"clientMsgType,omitempty"`
}

func (m *ClientPkgRequest) Reset()                    { *m = ClientPkgRequest{} }
func (m *ClientPkgRequest) String() string            { return proto.CompactTextString(m) }
func (*ClientPkgRequest) ProtoMessage()               {}
func (*ClientPkgRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ClientPkgRequest) GetCommonClientInfo() *CommonClientInfo {
	if m != nil {
		return m.CommonClientInfo
	}
	return nil
}

func (m *ClientPkgRequest) GetClientMsgType() ClientMsgType {
	if m != nil {
		return m.ClientMsgType
	}
	return ClientMsgType_AUTHENTICATE_CLIENT
}

type CommonServerResponse struct {
	ResponseHeader *common.ResponseHeader `protobuf:"bytes,1,opt,name=responseHeader" json:"responseHeader,omitempty"`
	ServerCmdType  ServerCmdType          `protobuf:"varint,2,opt,name=serverCmdType,enum=pnp.ServerCmdType" json:"serverCmdType,omitempty"`
}

func (m *CommonServerResponse) Reset()                    { *m = CommonServerResponse{} }
func (m *CommonServerResponse) String() string            { return proto.CompactTextString(m) }
func (*CommonServerResponse) ProtoMessage()               {}
func (*CommonServerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CommonServerResponse) GetResponseHeader() *common.ResponseHeader {
	if m != nil {
		return m.ResponseHeader
	}
	return nil
}

func (m *CommonServerResponse) GetServerCmdType() ServerCmdType {
	if m != nil {
		return m.ServerCmdType
	}
	return ServerCmdType_RUN
}

type ServerInstructionPayload struct {
	Cmd []string `protobuf:"bytes,1,rep,name=cmd" json:"cmd,omitempty"`
}

func (m *ServerInstructionPayload) Reset()                    { *m = ServerInstructionPayload{} }
func (m *ServerInstructionPayload) String() string            { return proto.CompactTextString(m) }
func (*ServerInstructionPayload) ProtoMessage()               {}
func (*ServerInstructionPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ServerInstructionPayload) GetCmd() []string {
	if m != nil {
		return m.Cmd
	}
	return nil
}

type PackageDetails struct {
	PackageName    string `protobuf:"bytes,1,opt,name=packageName" json:"packageName,omitempty"`
	PackageVersion string `protobuf:"bytes,2,opt,name=packageVersion" json:"packageVersion,omitempty"`
	AutoUpdate     bool   `protobuf:"varint,3,opt,name=autoUpdate" json:"autoUpdate,omitempty"`
}

func (m *PackageDetails) Reset()                    { *m = PackageDetails{} }
func (m *PackageDetails) String() string            { return proto.CompactTextString(m) }
func (*PackageDetails) ProtoMessage()               {}
func (*PackageDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PackageDetails) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *PackageDetails) GetPackageVersion() string {
	if m != nil {
		return m.PackageVersion
	}
	return ""
}

func (m *PackageDetails) GetAutoUpdate() bool {
	if m != nil {
		return m.AutoUpdate
	}
	return false
}

type ServerPkgResponse struct {
	CommonServerResponse     *CommonServerResponse     `protobuf:"bytes,1,opt,name=commonServerResponse" json:"commonServerResponse,omitempty"`
	ServerMsgType            ServerMsgType             `protobuf:"varint,2,opt,name=serverMsgType,enum=pnp.ServerMsgType" json:"serverMsgType,omitempty"`
	ServerInstructionPayload *ServerInstructionPayload `protobuf:"bytes,3,opt,name=serverInstructionPayload" json:"serverInstructionPayload,omitempty"`
	PackageDetails           *PackageDetails           `protobuf:"bytes,4,opt,name=packageDetails" json:"packageDetails,omitempty"`
}

func (m *ServerPkgResponse) Reset()                    { *m = ServerPkgResponse{} }
func (m *ServerPkgResponse) String() string            { return proto.CompactTextString(m) }
func (*ServerPkgResponse) ProtoMessage()               {}
func (*ServerPkgResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ServerPkgResponse) GetCommonServerResponse() *CommonServerResponse {
	if m != nil {
		return m.CommonServerResponse
	}
	return nil
}

func (m *ServerPkgResponse) GetServerMsgType() ServerMsgType {
	if m != nil {
		return m.ServerMsgType
	}
	return ServerMsgType_CLIENT_AUTHENTICATED
}

func (m *ServerPkgResponse) GetServerInstructionPayload() *ServerInstructionPayload {
	if m != nil {
		return m.ServerInstructionPayload
	}
	return nil
}

func (m *ServerPkgResponse) GetPackageDetails() *PackageDetails {
	if m != nil {
		return m.PackageDetails
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientInfo)(nil), "pnp.ClientInfo")
	proto.RegisterType((*CommonClientInfo)(nil), "pnp.CommonClientInfo")
	proto.RegisterType((*ClientPkgRequest)(nil), "pnp.ClientPkgRequest")
	proto.RegisterType((*CommonServerResponse)(nil), "pnp.CommonServerResponse")
	proto.RegisterType((*ServerInstructionPayload)(nil), "pnp.ServerInstructionPayload")
	proto.RegisterType((*PackageDetails)(nil), "pnp.PackageDetails")
	proto.RegisterType((*ServerPkgResponse)(nil), "pnp.ServerPkgResponse")
	proto.RegisterEnum("pnp.ClientMsgType", ClientMsgType_name, ClientMsgType_value)
	proto.RegisterEnum("pnp.ServerMsgType", ServerMsgType_name, ServerMsgType_value)
	proto.RegisterEnum("pnp.ServerCmdType", ServerCmdType_name, ServerCmdType_value)
}

func init() { proto.RegisterFile("pnp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 846 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0x5d, 0x6f, 0xa3, 0x46,
	0x14, 0x0d, 0x26, 0x9b, 0x38, 0xd7, 0xb1, 0x33, 0xb9, 0xf9, 0xa8, 0x13, 0x69, 0xab, 0xc8, 0x0f,
	0x55, 0x14, 0xad, 0xe2, 0xca, 0x7d, 0xa9, 0xb4, 0x52, 0x25, 0x16, 0xe3, 0x2c, 0x0a, 0xc6, 0x68,
	0xc0, 0x51, 0xbb, 0x2f, 0x88, 0x05, 0x9a, 0xb5, 0x36, 0x06, 0x0a, 0x64, 0xab, 0xed, 0x53, 0xff,
	0x41, 0xfb, 0x63, 0xfa, 0x2f, 0xfa, 0x7b, 0xfa, 0x5e, 0xcd, 0x30, 0xd8, 0x83, 0x93, 0xbc, 0x79,
	0xce, 0xb9, 0xf7, 0xdc, 0x33, 0x67, 0x86, 0x31, 0xec, 0x65, 0x49, 0x76, 0x9d, 0xe5, 0x69, 0x99,
	0xa2, 0x9a, 0x25, 0xd9, 0xf9, 0x9b, 0xfb, 0x45, 0xf9, 0xe9, 0xf1, 0xe3, 0x75, 0x98, 0x2e, 0x87,
	0x1f, 0x3c, 0x67, 0x98, 0x25, 0xd9, 0x30, 0x4c, 0x97, 0xcb, 0x34, 0x19, 0xf2, 0x2a, 0xb1, 0xa8,
	0x5a, 0x06, 0xbf, 0x03, 0xe8, 0x0f, 0x8b, 0x38, 0x29, 0xcd, 0xe4, 0xd7, 0x14, 0x4f, 0x61, 0x27,
	0x2d, 0xbc, 0xaf, 0x59, 0xdc, 0x57, 0x2e, 0x94, 0xcb, 0x3d, 0x2a, 0x56, 0x78, 0x0e, 0xed, 0xb4,
	0x98, 0x3c, 0x04, 0x5f, 0xd2, 0xbc, 0xdf, 0xe2, 0xcc, 0x6a, 0xcd, 0xb8, 0x20, 0x0f, 0x3f, 0xf1,
	0x2e, 0xb5, 0xe2, 0xea, 0x35, 0x9e, 0x41, 0x7b, 0xaa, 0xe9, 0x7e, 0x10, 0x45, 0x79, 0x7f, 0x9b,
	0x73, 0xbb, 0x53, 0x4d, 0xd7, 0xa2, 0x28, 0x1f, 0xfc, 0xa9, 0x00, 0xd1, 0xb9, 0x13, 0x69, 0xfe,
	0x5b, 0xe8, 0xe6, 0xf1, 0x6f, 0x8f, 0x71, 0x51, 0xbe, 0x8f, 0x83, 0x28, 0xce, 0xb9, 0x8d, 0xce,
	0xe8, 0xe4, 0x5a, 0x78, 0xa6, 0x32, 0x49, 0x9b, 0xb5, 0x38, 0x04, 0x08, 0x57, 0x52, 0xdc, 0x66,
	0x67, 0x74, 0x70, 0xcd, 0xd2, 0x59, 0x4f, 0xa0, 0x52, 0xc9, 0xe0, 0x2f, 0x66, 0x81, 0x2f, 0x9d,
	0xcf, 0xf7, 0x42, 0x1a, 0x35, 0x20, 0xe1, 0x86, 0xad, 0x95, 0x0b, 0xae, 0xb5, 0x41, 0xd2, 0x27,
	0xe5, 0xf8, 0x23, 0x74, 0xab, 0x29, 0xd3, 0xe2, 0x9e, 0xc7, 0xc2, 0xbc, 0xf4, 0x46, 0x28, 0x79,
	0x11, 0x0c, 0x6d, 0x16, 0x0e, 0xfe, 0x56, 0xe0, 0xb8, 0x1a, 0xe0, 0xc6, 0xf9, 0x97, 0x38, 0xa7,
	0x71, 0x91, 0xa5, 0x49, 0x11, 0xe3, 0x4f, 0xd0, 0xcb, 0xc5, 0xef, 0x46, 0x32, 0xa7, 0xeb, 0x64,
	0x64, 0x96, 0x6e, 0x54, 0x33, 0x4b, 0x05, 0x57, 0xd4, 0x97, 0xd1, 0x13, 0x4b, 0xae, 0xcc, 0xd0,
	0x66, 0xe1, 0xe0, 0x0d, 0xf4, 0x2b, 0xde, 0x4c, 0x8a, 0x32, 0x7f, 0x0c, 0xcb, 0x45, 0x9a, 0x38,
	0xc1, 0xd7, 0x87, 0x34, 0x88, 0x90, 0x80, 0x1a, 0x2e, 0xa3, 0xbe, 0x72, 0xa1, 0x5e, 0xee, 0x51,
	0xf6, 0x73, 0xf0, 0x07, 0xf4, 0x9c, 0x20, 0xfc, 0x1c, 0xdc, 0xc7, 0xe3, 0xb8, 0x0c, 0x16, 0x0f,
	0x05, 0x5e, 0x40, 0x27, 0xab, 0x10, 0x3b, 0x58, 0xd6, 0xf7, 0x4a, 0x86, 0xf0, 0x3b, 0xe8, 0x89,
	0xe5, 0x5d, 0x9c, 0x17, 0x8b, 0x34, 0x11, 0x57, 0x6c, 0x03, 0xc5, 0x6f, 0x01, 0x82, 0xc7, 0x32,
	0x9d, 0x67, 0x51, 0x50, 0x56, 0x57, 0xad, 0x4d, 0x25, 0x64, 0xf0, 0x4f, 0x0b, 0x0e, 0x2b, 0xab,
	0xfc, 0x38, 0x45, 0x72, 0x53, 0x38, 0x0e, 0x9f, 0x49, 0x54, 0xe4, 0x77, 0x26, 0x9d, 0x69, 0xb3,
	0x80, 0x3e, 0xdb, 0xb6, 0x0e, 0xf2, 0xb9, 0xb3, 0x75, 0x65, 0x86, 0x36, 0x0b, 0xf1, 0x17, 0xe8,
	0x17, 0x2f, 0x04, 0xc9, 0x37, 0xd3, 0x19, 0xbd, 0x96, 0x44, 0x9e, 0x16, 0xd1, 0x17, 0xdb, 0xf1,
	0xed, 0x2a, 0x41, 0x91, 0x3a, 0xff, 0xd8, 0x3a, 0xa3, 0x23, 0x2e, 0xd8, 0x3c, 0x10, 0xba, 0x51,
	0x7a, 0xf5, 0x5f, 0x0b, 0xba, 0x8d, 0x4b, 0x89, 0xdf, 0xc0, 0x91, 0x36, 0xf7, 0xde, 0x1b, 0xb6,
	0x67, 0xea, 0x9a, 0x67, 0xf8, 0xba, 0x65, 0x1a, 0xb6, 0x47, 0xb6, 0x90, 0xc0, 0xbe, 0x73, 0x7b,
	0xe3, 0x1b, 0xf6, 0x9d, 0x6f, 0xda, 0xa6, 0x47, 0x14, 0x56, 0x2a, 0x23, 0xa6, 0x66, 0x99, 0x1f,
	0x8c, 0x31, 0x69, 0xe1, 0x6b, 0x38, 0x7b, 0x4a, 0xf8, 0x13, 0xcd, 0xb4, 0x8c, 0x31, 0x51, 0xf1,
	0x04, 0x0e, 0x19, 0x6d, 0xcf, 0x3c, 0xdf, 0xb4, 0x5d, 0x4f, 0xb3, 0x18, 0xbc, 0x8d, 0x87, 0xd0,
	0x65, 0xf0, 0x1a, 0x7a, 0x85, 0x7d, 0x38, 0x66, 0xd0, 0x9d, 0x41, 0x5d, 0x73, 0x66, 0xfb, 0xb3,
	0xb9, 0x37, 0xd6, 0x3c, 0x63, 0x4c, 0x76, 0xf0, 0x14, 0x50, 0x66, 0x2c, 0xcd, 0x33, 0x5c, 0x8f,
	0xec, 0xe2, 0x19, 0x9c, 0x30, 0x7c, 0x6e, 0x0b, 0x19, 0xdf, 0x9d, 0xeb, 0xba, 0xe1, 0xba, 0xa4,
	0x5d, 0x8b, 0xad, 0x29, 0x61, 0x68, 0xaf, 0xde, 0xc8, 0x66, 0x0b, 0xd4, 0x53, 0x36, 0x1a, 0x3a,
	0xb5, 0x14, 0x9d, 0x59, 0xd6, 0x3b, 0x4d, 0xbf, 0x5d, 0x75, 0xec, 0xd7, 0x52, 0x2b, 0x46, 0xb4,
	0x74, 0x71, 0x1f, 0xda, 0x37, 0x86, 0xe7, 0xdb, 0xc6, 0xcf, 0x1e, 0xe9, 0x5d, 0xfd, 0xab, 0x40,
	0xb7, 0x71, 0x61, 0x98, 0x64, 0x15, 0xb5, 0x2f, 0xc7, 0x3f, 0x26, 0x5b, 0x88, 0xd0, 0x93, 0x52,
	0x34, 0xec, 0x3b, 0xa2, 0xe0, 0x31, 0x10, 0xd3, 0xf5, 0x9b, 0x71, 0xb5, 0xf0, 0x00, 0x3a, 0xb5,
	0x55, 0xe7, 0xf6, 0x86, 0xa8, 0x2c, 0x0d, 0x09, 0xf0, 0x27, 0x74, 0x36, 0xf5, 0x27, 0xa6, 0x65,
	0x90, 0x6d, 0x3c, 0x82, 0x03, 0xa1, 0xb0, 0x4a, 0xf5, 0x15, 0x3b, 0x82, 0x75, 0x3c, 0x4c, 0x62,
	0x87, 0x1d, 0xfb, 0x6a, 0x33, 0x0c, 0xd9, 0x65, 0x48, 0xbd, 0x13, 0x8e, 0xb4, 0xaf, 0x8c, 0x7a,
	0x33, 0xe2, 0xdd, 0xc0, 0x5d, 0x50, 0xe9, 0xdc, 0x26, 0x5b, 0xd8, 0x86, 0x6d, 0xd3, 0x9e, 0xcc,
	0x88, 0x82, 0x3d, 0x00, 0xdd, 0x9a, 0xb9, 0x86, 0xaf, 0xcf, 0x6c, 0x9b, 0xb4, 0xd8, 0xa8, 0xa9,
	0x66, 0xcf, 0x35, 0xcb, 0x9f, 0x3b, 0x6c, 0x3c, 0x51, 0x47, 0x26, 0xa8, 0x4e, 0xe2, 0xe0, 0x3b,
	0xe8, 0xdc, 0xc4, 0xa5, 0xb8, 0xb8, 0x05, 0x9e, 0x48, 0x2f, 0xe7, 0xfa, 0xa9, 0x3e, 0x3f, 0x95,
	0xbe, 0x17, 0xe9, 0x93, 0x1f, 0x6c, 0x5d, 0x2a, 0xdf, 0x2b, 0x1f, 0x77, 0xf8, 0x1f, 0xdc, 0x0f,
	0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x95, 0xdb, 0xa5, 0xda, 0x20, 0x07, 0x00, 0x00,
}
