// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pnp.proto

/*
Package pnp is a generated protocol buffer package.

It is generated from these files:
	pnp.proto

It has these top-level messages:
	ClientInfo
	CommonClientInfo
	ClientPkgRequest
	CommonServerResponse
	ServerInstructionPayload
	ServerPkgResponse
*/
package pnp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/ZTP/pnp/common/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClientMsgType int32

const (
	ClientMsgType_PKG_ZTP_INIT          ClientMsgType = 0
	ClientMsgType_PKG_NOT_INSTALLED     ClientMsgType = 1
	ClientMsgType_PKG_INSTALLED         ClientMsgType = 2
	ClientMsgType_PKG_VERSION_CHANGED   ClientMsgType = 3
	ClientMsgType_PKG_VERSION_NO_CHANGE ClientMsgType = 4
	ClientMsgType_PKG_UNINSTALL_SUCCESS ClientMsgType = 5
	ClientMsgType_PKG_UNINSTALL_FAILED  ClientMsgType = 6
	ClientMsgType_PKG_INSTALL_SUCCESS   ClientMsgType = 7
	ClientMsgType_PKG_INSTALL_FAILED    ClientMsgType = 8
)

var ClientMsgType_name = map[int32]string{
	0: "PKG_ZTP_INIT",
	1: "PKG_NOT_INSTALLED",
	2: "PKG_INSTALLED",
	3: "PKG_VERSION_CHANGED",
	4: "PKG_VERSION_NO_CHANGE",
	5: "PKG_UNINSTALL_SUCCESS",
	6: "PKG_UNINSTALL_FAILED",
	7: "PKG_INSTALL_SUCCESS",
	8: "PKG_INSTALL_FAILED",
}
var ClientMsgType_value = map[string]int32{
	"PKG_ZTP_INIT":          0,
	"PKG_NOT_INSTALLED":     1,
	"PKG_INSTALLED":         2,
	"PKG_VERSION_CHANGED":   3,
	"PKG_VERSION_NO_CHANGE": 4,
	"PKG_UNINSTALL_SUCCESS": 5,
	"PKG_UNINSTALL_FAILED":  6,
	"PKG_INSTALL_SUCCESS":   7,
	"PKG_INSTALL_FAILED":    8,
}

func (x ClientMsgType) String() string {
	return proto.EnumName(ClientMsgType_name, int32(x))
}
func (ClientMsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ServerMsgType int32

const (
	ServerMsgType_IS_PKG_INSTALLED      ServerMsgType = 0
	ServerMsgType_INSTALL_PKG           ServerMsgType = 1
	ServerMsgType_INSTALL_PKG_FROM_FILE ServerMsgType = 2
	ServerMsgType_IS_PKG_OUTDATED       ServerMsgType = 3
	ServerMsgType_UNINSTALL_PKG         ServerMsgType = 4
	ServerMsgType_GET_NEXT_PKG          ServerMsgType = 5
)

var ServerMsgType_name = map[int32]string{
	0: "IS_PKG_INSTALLED",
	1: "INSTALL_PKG",
	2: "INSTALL_PKG_FROM_FILE",
	3: "IS_PKG_OUTDATED",
	4: "UNINSTALL_PKG",
	5: "GET_NEXT_PKG",
}
var ServerMsgType_value = map[string]int32{
	"IS_PKG_INSTALLED":      0,
	"INSTALL_PKG":           1,
	"INSTALL_PKG_FROM_FILE": 2,
	"IS_PKG_OUTDATED":       3,
	"UNINSTALL_PKG":         4,
	"GET_NEXT_PKG":          5,
}

func (x ServerMsgType) String() string {
	return proto.EnumName(ServerMsgType_name, int32(x))
}
func (ServerMsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ServerCmdType int32

const (
	ServerCmdType_RUN        ServerCmdType = 0
	ServerCmdType_CONFIG     ServerCmdType = 1
	ServerCmdType_INFO       ServerCmdType = 2
	ServerCmdType_CLOSE_CONN ServerCmdType = 3
)

var ServerCmdType_name = map[int32]string{
	0: "RUN",
	1: "CONFIG",
	2: "INFO",
	3: "CLOSE_CONN",
}
var ServerCmdType_value = map[string]int32{
	"RUN":        0,
	"CONFIG":     1,
	"INFO":       2,
	"CLOSE_CONN": 3,
}

func (x ServerCmdType) String() string {
	return proto.EnumName(ServerCmdType_name, int32(x))
}
func (ServerCmdType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ClientInfo struct {
	OsType   string `protobuf:"bytes,1,opt,name=osType" json:"osType,omitempty"`
	OsFlavor string `protobuf:"bytes,2,opt,name=osFlavor" json:"osFlavor,omitempty"`
	ArchType string `protobuf:"bytes,3,opt,name=archType" json:"archType,omitempty"`
	MACAddr  string `protobuf:"bytes,4,opt,name=MAC_addr,json=MACAddr" json:"MAC_addr,omitempty"`
}

func (m *ClientInfo) Reset()                    { *m = ClientInfo{} }
func (m *ClientInfo) String() string            { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()               {}
func (*ClientInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ClientInfo) GetOsType() string {
	if m != nil {
		return m.OsType
	}
	return ""
}

func (m *ClientInfo) GetOsFlavor() string {
	if m != nil {
		return m.OsFlavor
	}
	return ""
}

func (m *ClientInfo) GetArchType() string {
	if m != nil {
		return m.ArchType
	}
	return ""
}

func (m *ClientInfo) GetMACAddr() string {
	if m != nil {
		return m.MACAddr
	}
	return ""
}

type CommonClientInfo struct {
	RequestHeader *common.RequestHeader `protobuf:"bytes,1,opt,name=requestHeader" json:"requestHeader,omitempty"`
	ClientInfo    *ClientInfo           `protobuf:"bytes,2,opt,name=clientInfo" json:"clientInfo,omitempty"`
}

func (m *CommonClientInfo) Reset()                    { *m = CommonClientInfo{} }
func (m *CommonClientInfo) String() string            { return proto.CompactTextString(m) }
func (*CommonClientInfo) ProtoMessage()               {}
func (*CommonClientInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CommonClientInfo) GetRequestHeader() *common.RequestHeader {
	if m != nil {
		return m.RequestHeader
	}
	return nil
}

func (m *CommonClientInfo) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

type ClientPkgRequest struct {
	CommonClientInfo *CommonClientInfo `protobuf:"bytes,1,opt,name=commonClientInfo" json:"commonClientInfo,omitempty"`
	ClientMsgType    ClientMsgType     `protobuf:"varint,2,opt,name=clientMsgType,enum=pnp.ClientMsgType" json:"clientMsgType,omitempty"`
}

func (m *ClientPkgRequest) Reset()                    { *m = ClientPkgRequest{} }
func (m *ClientPkgRequest) String() string            { return proto.CompactTextString(m) }
func (*ClientPkgRequest) ProtoMessage()               {}
func (*ClientPkgRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ClientPkgRequest) GetCommonClientInfo() *CommonClientInfo {
	if m != nil {
		return m.CommonClientInfo
	}
	return nil
}

func (m *ClientPkgRequest) GetClientMsgType() ClientMsgType {
	if m != nil {
		return m.ClientMsgType
	}
	return ClientMsgType_PKG_ZTP_INIT
}

type CommonServerResponse struct {
	ResponseHeader *common.ResponseHeader `protobuf:"bytes,1,opt,name=responseHeader" json:"responseHeader,omitempty"`
	ServerCmdType  ServerCmdType          `protobuf:"varint,2,opt,name=serverCmdType,enum=pnp.ServerCmdType" json:"serverCmdType,omitempty"`
}

func (m *CommonServerResponse) Reset()                    { *m = CommonServerResponse{} }
func (m *CommonServerResponse) String() string            { return proto.CompactTextString(m) }
func (*CommonServerResponse) ProtoMessage()               {}
func (*CommonServerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CommonServerResponse) GetResponseHeader() *common.ResponseHeader {
	if m != nil {
		return m.ResponseHeader
	}
	return nil
}

func (m *CommonServerResponse) GetServerCmdType() ServerCmdType {
	if m != nil {
		return m.ServerCmdType
	}
	return ServerCmdType_RUN
}

type ServerInstructionPayload struct {
	Cmd []string `protobuf:"bytes,1,rep,name=cmd" json:"cmd,omitempty"`
}

func (m *ServerInstructionPayload) Reset()                    { *m = ServerInstructionPayload{} }
func (m *ServerInstructionPayload) String() string            { return proto.CompactTextString(m) }
func (*ServerInstructionPayload) ProtoMessage()               {}
func (*ServerInstructionPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ServerInstructionPayload) GetCmd() []string {
	if m != nil {
		return m.Cmd
	}
	return nil
}

type ServerPkgResponse struct {
	CommonServerResponse     *CommonServerResponse     `protobuf:"bytes,1,opt,name=commonServerResponse" json:"commonServerResponse,omitempty"`
	ServerMsgType            ServerMsgType             `protobuf:"varint,2,opt,name=serverMsgType,enum=pnp.ServerMsgType" json:"serverMsgType,omitempty"`
	ServerInstructionPayload *ServerInstructionPayload `protobuf:"bytes,3,opt,name=serverInstructionPayload" json:"serverInstructionPayload,omitempty"`
}

func (m *ServerPkgResponse) Reset()                    { *m = ServerPkgResponse{} }
func (m *ServerPkgResponse) String() string            { return proto.CompactTextString(m) }
func (*ServerPkgResponse) ProtoMessage()               {}
func (*ServerPkgResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ServerPkgResponse) GetCommonServerResponse() *CommonServerResponse {
	if m != nil {
		return m.CommonServerResponse
	}
	return nil
}

func (m *ServerPkgResponse) GetServerMsgType() ServerMsgType {
	if m != nil {
		return m.ServerMsgType
	}
	return ServerMsgType_IS_PKG_INSTALLED
}

func (m *ServerPkgResponse) GetServerInstructionPayload() *ServerInstructionPayload {
	if m != nil {
		return m.ServerInstructionPayload
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientInfo)(nil), "pnp.ClientInfo")
	proto.RegisterType((*CommonClientInfo)(nil), "pnp.CommonClientInfo")
	proto.RegisterType((*ClientPkgRequest)(nil), "pnp.ClientPkgRequest")
	proto.RegisterType((*CommonServerResponse)(nil), "pnp.CommonServerResponse")
	proto.RegisterType((*ServerInstructionPayload)(nil), "pnp.ServerInstructionPayload")
	proto.RegisterType((*ServerPkgResponse)(nil), "pnp.ServerPkgResponse")
	proto.RegisterEnum("pnp.ClientMsgType", ClientMsgType_name, ClientMsgType_value)
	proto.RegisterEnum("pnp.ServerMsgType", ServerMsgType_name, ServerMsgType_value)
	proto.RegisterEnum("pnp.ServerCmdType", ServerCmdType_name, ServerCmdType_value)
}

func init() { proto.RegisterFile("pnp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 679 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x41, 0x4f, 0xdb, 0x4a,
	0x10, 0x8e, 0xe3, 0x10, 0xc2, 0xe4, 0x05, 0x36, 0x4b, 0x92, 0x67, 0x90, 0x9e, 0x84, 0x7c, 0x42,
	0x08, 0x25, 0x4f, 0x79, 0x97, 0x27, 0x55, 0x42, 0x72, 0x8d, 0x13, 0x2c, 0x12, 0xdb, 0x5a, 0x3b,
	0x55, 0xcb, 0xc5, 0x32, 0xb6, 0x1b, 0x10, 0xc4, 0x76, 0x6d, 0x43, 0xc5, 0xad, 0xf7, 0x1e, 0xda,
	0x3f, 0xd9, 0xdf, 0xd0, 0x6b, 0xb5, 0x1b, 0x87, 0xac, 0x03, 0xdc, 0x3c, 0xf3, 0x7d, 0x33, 0xf3,
	0xcd, 0x97, 0xc9, 0xc2, 0x4e, 0x12, 0x25, 0xfd, 0x24, 0x8d, 0xf3, 0x18, 0x8b, 0x49, 0x94, 0x1c,
	0x9e, 0xce, 0x6f, 0xf3, 0x9b, 0x87, 0xeb, 0xbe, 0x1f, 0x2f, 0x06, 0x57, 0x8e, 0x35, 0x48, 0xa2,
	0x64, 0xe0, 0xc7, 0x8b, 0x45, 0x1c, 0x0d, 0x18, 0xab, 0x08, 0x96, 0x25, 0xf2, 0x57, 0x00, 0xf5,
	0xfe, 0x36, 0x8c, 0x72, 0x3d, 0xfa, 0x1c, 0xe3, 0x1e, 0xd4, 0xe3, 0xcc, 0x79, 0x4a, 0x42, 0x49,
	0x38, 0x12, 0x8e, 0x77, 0x48, 0x11, 0xe1, 0x43, 0x68, 0xc4, 0xd9, 0xe8, 0xde, 0x7b, 0x8c, 0x53,
	0xa9, 0xca, 0x90, 0xe7, 0x98, 0x62, 0x5e, 0xea, 0xdf, 0xb0, 0x2a, 0x71, 0x89, 0xad, 0x62, 0x7c,
	0x00, 0x8d, 0xa9, 0xa2, 0xba, 0x5e, 0x10, 0xa4, 0x52, 0x8d, 0x61, 0xdb, 0x53, 0x45, 0x55, 0x82,
	0x20, 0x95, 0xbf, 0x09, 0x80, 0x54, 0xa6, 0x84, 0x9b, 0xff, 0x0e, 0x5a, 0x69, 0xf8, 0xe5, 0x21,
	0xcc, 0xf2, 0x8b, 0xd0, 0x0b, 0xc2, 0x94, 0xc9, 0x68, 0x0e, 0xbb, 0xfd, 0x42, 0x33, 0xe1, 0x41,
	0x52, 0xe6, 0xe2, 0x01, 0x80, 0xff, 0xdc, 0x8a, 0xc9, 0x6c, 0x0e, 0xf7, 0xfa, 0xd4, 0x9d, 0xf5,
	0x04, 0xc2, 0x51, 0xe4, 0x1f, 0x54, 0x02, 0x0b, 0xad, 0xbb, 0x79, 0xd1, 0x1a, 0x2b, 0x80, 0xfc,
	0x0d, 0x59, 0xcf, 0x2a, 0x58, 0xaf, 0x0d, 0x90, 0xbc, 0xa0, 0xe3, 0xff, 0xa1, 0xb5, 0x9c, 0x32,
	0xcd, 0xe6, 0xcc, 0x16, 0xaa, 0x65, 0x77, 0x88, 0x39, 0x2d, 0x05, 0x42, 0xca, 0x44, 0xf9, 0xa7,
	0x00, 0x9d, 0xe5, 0x00, 0x3b, 0x4c, 0x1f, 0xc3, 0x94, 0x84, 0x59, 0x12, 0x47, 0x59, 0x88, 0xcf,
	0x60, 0x37, 0x2d, 0xbe, 0x4b, 0xce, 0xf4, 0xd6, 0xce, 0xf0, 0x28, 0xd9, 0x60, 0x53, 0x49, 0x19,
	0xeb, 0xa8, 0x2e, 0x82, 0x17, 0x92, 0x6c, 0x1e, 0x21, 0x65, 0xa2, 0x7c, 0x0a, 0xd2, 0x12, 0xd7,
	0xa3, 0x2c, 0x4f, 0x1f, 0xfc, 0xfc, 0x36, 0x8e, 0x2c, 0xef, 0xe9, 0x3e, 0xf6, 0x02, 0x8c, 0x40,
	0xf4, 0x17, 0x81, 0x24, 0x1c, 0x89, 0xc7, 0x3b, 0x84, 0x7e, 0xca, 0xbf, 0x05, 0x68, 0x2f, 0xe9,
	0xcc, 0xd2, 0x42, 0xfd, 0x14, 0x3a, 0xfe, 0x2b, 0x5b, 0x15, 0x3b, 0x1c, 0x70, 0xbe, 0x96, 0x09,
	0xe4, 0xd5, 0xb2, 0xf5, 0x32, 0xaf, 0xf9, 0x6b, 0xf3, 0x08, 0x29, 0x13, 0xf1, 0x27, 0x90, 0xb2,
	0x37, 0x96, 0x61, 0xb7, 0xdb, 0x1c, 0xfe, 0xc3, 0x35, 0x79, 0x49, 0x22, 0x6f, 0x96, 0x9f, 0xfc,
	0x12, 0xa0, 0x55, 0xfa, 0x6d, 0x31, 0x82, 0xbf, 0xac, 0xcb, 0xb1, 0x7b, 0xe5, 0x58, 0xae, 0x6e,
	0xe8, 0x0e, 0xaa, 0xe0, 0x2e, 0xb4, 0x69, 0xc6, 0x30, 0x1d, 0x57, 0x37, 0x6c, 0x47, 0x99, 0x4c,
	0xb4, 0x73, 0x24, 0xe0, 0x36, 0xb4, 0x68, 0x7a, 0x9d, 0xaa, 0xe2, 0xbf, 0x61, 0x9f, 0xa6, 0x3e,
	0x68, 0xc4, 0xd6, 0x4d, 0xc3, 0x55, 0x2f, 0x14, 0x63, 0xac, 0x9d, 0x23, 0x11, 0x1f, 0x40, 0x97,
	0x07, 0x0c, 0xb3, 0xc0, 0x50, 0x6d, 0x05, 0xcd, 0x8c, 0xa2, 0x91, 0x6b, 0xcf, 0x54, 0x55, 0xb3,
	0x6d, 0xb4, 0x85, 0x25, 0xe8, 0x94, 0xa1, 0x91, 0xa2, 0xd3, 0x41, 0xf5, 0xd5, 0xa0, 0xcd, 0x92,
	0x6d, 0xdc, 0x03, 0xcc, 0x03, 0x45, 0x41, 0xe3, 0xe4, 0xbb, 0x00, 0xad, 0x92, 0xc7, 0xb8, 0x03,
	0x48, 0xb7, 0xdd, 0xf2, 0x06, 0x15, 0xbc, 0x07, 0xcd, 0x55, 0xad, 0x75, 0x39, 0x46, 0x02, 0x95,
	0xc7, 0x25, 0xdc, 0x11, 0x31, 0xa7, 0xee, 0x48, 0x9f, 0x68, 0xa8, 0x8a, 0xf7, 0x61, 0xaf, 0xe8,
	0x60, 0xce, 0x9c, 0x73, 0xc5, 0x61, 0x9b, 0xb6, 0xa1, 0xb5, 0xd6, 0x4b, 0x5b, 0xd4, 0xa8, 0xa3,
	0x63, 0xcd, 0x71, 0x0d, 0xed, 0xa3, 0xc3, 0x32, 0x5b, 0x27, 0x67, 0x2b, 0x31, 0xc5, 0xb9, 0xe2,
	0x6d, 0x10, 0xc9, 0xcc, 0x40, 0x15, 0x0c, 0x50, 0x57, 0x4d, 0x63, 0xa4, 0xd3, 0xd1, 0x0d, 0xa8,
	0xe9, 0xc6, 0xc8, 0x44, 0x55, 0xbc, 0x0b, 0xa0, 0x4e, 0x4c, 0x5b, 0x73, 0x55, 0xd3, 0x30, 0x90,
	0x38, 0xd4, 0x41, 0xb4, 0x22, 0x0b, 0xbf, 0x87, 0xe6, 0x38, 0xcc, 0x2d, 0xcf, 0xbf, 0xf3, 0xe6,
	0x61, 0x86, 0xbb, 0xdc, 0x3f, 0x75, 0xfd, 0x34, 0x1c, 0xf6, 0xb8, 0xdb, 0xe0, 0xce, 0x5b, 0xae,
	0x1c, 0x0b, 0xff, 0x0a, 0xd7, 0x75, 0xf6, 0xa0, 0xfe, 0xf7, 0x27, 0x00, 0x00, 0xff, 0xff, 0xbc,
	0x96, 0x84, 0x1b, 0x90, 0x05, 0x00, 0x00,
}
