// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	common.proto

It has these top-level messages:
	RequestHeader
	ResponseHeader
	Identifiers
*/
package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Contains the common header information that is sent with a request.
type RequestHeader struct {
	Identifiers      *Identifiers               `protobuf:"bytes,1,opt,name=Identifiers" json:"Identifiers,omitempty"`
	RequestTimestamp *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=RequestTimestamp" json:"RequestTimestamp,omitempty"`
}

func (m *RequestHeader) Reset()                    { *m = RequestHeader{} }
func (m *RequestHeader) String() string            { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()               {}
func (*RequestHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestHeader) GetIdentifiers() *Identifiers {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

func (m *RequestHeader) GetRequestTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.RequestTimestamp
	}
	return nil
}

// *
// Contains the common header information that is sent with a response.
type ResponseHeader struct {
	Identifiers       *Identifiers               `protobuf:"bytes,1,opt,name=Identifiers" json:"Identifiers,omitempty"`
	ResponseTimestamp *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=ResponseTimestamp" json:"ResponseTimestamp,omitempty"`
}

func (m *ResponseHeader) Reset()                    { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string            { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()               {}
func (*ResponseHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseHeader) GetIdentifiers() *Identifiers {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

func (m *ResponseHeader) GetResponseTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.ResponseTimestamp
	}
	return nil
}

// *
// Contains the identifiers used to uniquely identify a request or response.
type Identifiers struct {
	TraceID   string `protobuf:"bytes,1,opt,name=TraceID" json:"TraceID,omitempty"`
	MessageID string `protobuf:"bytes,2,opt,name=MessageID" json:"MessageID,omitempty"`
}

func (m *Identifiers) Reset()                    { *m = Identifiers{} }
func (m *Identifiers) String() string            { return proto.CompactTextString(m) }
func (*Identifiers) ProtoMessage()               {}
func (*Identifiers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Identifiers) GetTraceID() string {
	if m != nil {
		return m.TraceID
	}
	return ""
}

func (m *Identifiers) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "common.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "common.ResponseHeader")
	proto.RegisterType((*Identifiers)(nil), "common.Identifiers")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x8e, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0xc7, 0x95, 0x0e, 0x45, 0xbd, 0x02, 0x02, 0xb3, 0x44, 0x15, 0x03, 0xca, 0xc4, 0xe4, 0x48,
	0x20, 0x26, 0x56, 0x40, 0xed, 0xc0, 0x62, 0xf5, 0x05, 0x9c, 0xf4, 0x6a, 0x22, 0xd5, 0x3e, 0xe3,
	0x73, 0x06, 0x5e, 0x02, 0x89, 0x37, 0x46, 0xb8, 0x35, 0x2d, 0xca, 0x84, 0xba, 0xf9, 0xfc, 0xff,
	0xfa, 0xc1, 0x69, 0x4b, 0xd6, 0x92, 0x93, 0x3e, 0x50, 0x24, 0x31, 0xde, 0x5e, 0xb3, 0x47, 0xd3,
	0xc5, 0xb7, 0xbe, 0x91, 0x2d, 0xd9, 0xda, 0xd0, 0x46, 0x3b, 0x53, 0x27, 0x43, 0xd3, 0xaf, 0x6b,
	0x1f, 0x3f, 0x3c, 0x72, 0x1d, 0x3b, 0x8b, 0x1c, 0xb5, 0xf5, 0xfb, 0xd7, 0xb6, 0xa4, 0xfa, 0x2c,
	0xe0, 0x4c, 0xe1, 0x7b, 0x8f, 0x1c, 0xe7, 0xa8, 0x57, 0x18, 0xc4, 0x03, 0x4c, 0x17, 0x2b, 0x74,
	0xb1, 0x5b, 0x77, 0x18, 0xb8, 0x2c, 0x6e, 0x8a, 0xdb, 0xe9, 0xdd, 0x95, 0xdc, 0x4d, 0x1f, 0x48,
	0xea, 0xd0, 0x27, 0x5e, 0xe0, 0x62, 0xd7, 0xb3, 0xcc, 0x13, 0xe5, 0x28, 0x65, 0x67, 0xd2, 0x10,
	0x99, 0x0d, 0xca, 0x4c, 0x25, 0x7f, 0x1d, 0x6a, 0x90, 0xa9, 0xbe, 0x0a, 0x38, 0x57, 0xc8, 0x9e,
	0x1c, 0xe3, 0x71, 0x44, 0x73, 0xb8, 0xcc, 0x45, 0xff, 0x41, 0x1a, 0x86, 0xaa, 0xe7, 0x3f, 0x00,
	0xa2, 0x84, 0x93, 0x65, 0xd0, 0x2d, 0x2e, 0x9e, 0x12, 0xcb, 0x44, 0xe5, 0x53, 0x5c, 0xc3, 0xe4,
	0x15, 0x99, 0xb5, 0xf9, 0xd1, 0x46, 0x49, 0xdb, 0x7f, 0x34, 0xe3, 0xb4, 0x76, 0xff, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0x53, 0x35, 0x9a, 0xbf, 0xc7, 0x01, 0x00, 0x00,
}
