// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: certificate.proto

/*
Package certificate is a generated protocol buffer package.

It is generated from these files:
	certificate.proto

It has these top-level messages:
	ClientMACInfo
	ServerCertificate
*/
package certificate

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/RiverbedTechnology/sdp-ztp/pnp/pnp-proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Certificate service

type CertificateService interface {
	GetCertificates(ctx context.Context, in *ClientMACInfo, opts ...client.CallOption) (*ServerCertificate, error)
}

type certificateService struct {
	c           client.Client
	serviceName string
}

func CertificateServiceClient(serviceName string, c client.Client) CertificateService {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "certificate"
	}
	return &certificateService{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *certificateService) GetCertificates(ctx context.Context, in *ClientMACInfo, opts ...client.CallOption) (*ServerCertificate, error) {
	req := c.c.NewRequest(c.serviceName, "Certificate.GetCertificates", in)
	out := new(ServerCertificate)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Certificate service

type CertificateHandler interface {
	GetCertificates(context.Context, *ClientMACInfo, *ServerCertificate) error
}

func RegisterCertificateHandler(s server.Server, hdlr CertificateHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Certificate{hdlr}, opts...))
}

type Certificate struct {
	CertificateHandler
}

func (h *Certificate) GetCertificates(ctx context.Context, in *ClientMACInfo, out *ServerCertificate) error {
	return h.CertificateHandler.GetCertificates(ctx, in, out)
}
